# .github/workflows/check.yaml 

name: Hisse Fiyati Kontrolu # (İsmi de güncelledim)

on:
  schedule:
    # --- DEĞİŞİKLİK 1 ---
    # API limitini aşmamak için "her 15 dakikada bir" yerine
    # "her saatin başında" (saatte bir) çalışacak şekilde değiştirildi.
    - cron: '0 * * * *'
  
  # "Actions" sekmesinden elle tetiklemeyi de etkinleştirir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v3

      - name: Python 3.10 Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kütüphaneleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hisse Izleyiciyi Çalıştır # (Adımı da güncelledim)
        env:
          # --- DEĞİKLİK 2 ---
          # Hisse senedi API anahtarını Python koduna aktarmak
          # için bu satır eklendi.
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          
          # Mevcut sırlarımız da burada kalıyor
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
        run: python kur_izleyici.py
